# Generated by Django 4.2.4 on 2023-08-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0002_alter_user_firtname_alter_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firtname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
