# Generated by Django 4.2.4 on 2023-08-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0004_user_phone_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rpassword',
            field=models.CharField(max_length=150, null=True, verbose_name='Entrez à nouveau votre mot de passe'),
        ),
    ]
