# Generated by Django 4.2.4 on 2023-08-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0005_user_rpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
