# Generated by Django 4.2.4 on 2023-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0006_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address (facultatif)'),
        ),
    ]
