# Generated by Django 4.2.3 on 2023-07-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
