# Generated by Django 4.2.3 on 2023-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vente', '0002_delete_object_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dimension', models.CharField(max_length=150, verbose_name='Dimension')),
                ('description', models.TextField(default='Object description not available!', max_length=1000, verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(verbose_name='Price')),
                ('image', models.ImageField(default='C:\\Users\\berth\\3D Objects\\3DW\\object3d\\vente\\static\\img\\2023\\07\\19\\support_main.PNG', upload_to='static/img/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('password', models.CharField(max_length=150, verbose_name='Entrez votre mot de passe')),
                ('rpassword', models.CharField(max_length=150, null=True, verbose_name='Entrez à nouveau votre mot de passe')),
            ],
        ),
    ]
