# Generated by Django 4.2.4 on 2023-08-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dimension', models.CharField(max_length=150, verbose_name='Dimension')),
                ('description', models.TextField(default='Object description not available!', max_length=1000, verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(verbose_name='Price')),
                ('image', models.ImageField(default='C:\\Users\\berth\\3D Objects\\3DW\\object3d\\vente\\static\\img\\2023\\07\\19\\support_main.PNG', upload_to='static/img/%Y/%m/%d/')),
            ],
        ),
    ]
