# Generated by Django 4.2.4 on 2023-10-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Product',
        ),
    ]
