# Generated by Django 4.2.6 on 2023-10-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0004_rename_created_cart_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='sale_point.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
