# Generated by Django 4.2.6 on 2023-10-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0005_remove_cart_creation_date_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
