# Generated by Django 4.2.6 on 2023-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0007_remove_cart_customer_customer_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paylink',
            field=models.CharField(default='#', max_length=100, verbose_name='Paylink'),
            preserve_default=False,
        ),
    ]
