# Generated by Django 4.2.6 on 2023-11-12 08:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0008_product_paylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=django_mysql.models.ListCharField(models.IntegerField(), default='', max_length=1000000000, size=None),
            preserve_default=False,
        ),
    ]
