# Generated by Django 4.2.6 on 2023-11-12 08:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0009_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=1000000000, null=True, size=None),
        ),
    ]
