# Generated by Django 4.2.6 on 2023-11-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0013_product_price_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paylink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\berth\\3D Objects\\3DW\\object3d\\vente\\static\\img\\2023\\07\\19\\support_main.PNG', upload_to='static/img/%Y/'),
        ),
    ]
