# Generated by Django 4.2.6 on 2023-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0014_remove_product_paylink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/default/car.jpg', upload_to='static/img/%Y/'),
        ),
    ]
