# Generated by Django 4.2.6 on 2023-11-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_point', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/default/default_product.png', upload_to='static/img/%Y/'),
        ),
    ]
